GET http://localhost:3002/api/comment/post/11210961-3aee-4501-a2e4-4005f2018772 HTTP/1.1

###

POST http://localhost:3002/api/comment HTTP/1.1
Content-Type: application/json

{
    "postId": "11210961-3aee-4501-a2e4-4005f2018772",
    "text": "This is a comment",
    "authorId": "1"
}

###

DELETE  http://localhost:3002/api/comment/c8e59928-5037-453b-9ef1-9c02b0d24d2c HTTP/1.1
