version: '3.9'
services:
  readme.file.mongo:
    image: mongo:4.4
    restart: always
    container_name: readme.file.mongo

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE}

    ports:
      - 27018:27017

    volumes:
      - readme.mongo.files:/data/db

    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27018/${MONGODB_DATABASE} --quiet
      interval: 10s
      timeout: 10s
      retries: 5

volumes:
  readme.mongo.files:
