POST http://localhost:3000/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "email": "abus@gmail.com",
  "password": "123456",
  "firstName": "bogna",
  "lastName": "bogna"
}

###

POST http://localhost:3000/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "abus@gmail.com",
  "password": "123"
}

###

GET http://localhost:3000/api/auth/659c14009d0fb85ff6cc932d HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1YWU4ODQ4NzBhNDYyYjc5MmRmMWU1NSIsImVtYWlsIjoiYWJ1c0BnbWFpbC5jb20iLCJmaXJzdE5hbWUiOiJib2duYSIsImxhc3ROYW1lIjoiYm9nbmEiLCJhdmF0YXIiOiIiLCJpYXQiOjE3MDU5MzY5OTgsImV4cCI6MTcwNjAyMzM5OH0.pTrBhYrpGHCAIT1f1zd9xOgdpdYJKshXkjDoxWuHCUs
###

PUT http://localhost:3000/api/auth HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1OWMxNDAwOWQwZmI4NWZmNmNjOTMyZCIsImVtYWlsIjoiY2J2QGdtYWlsLmNvbSIsImZpcnN0TmFtZSI6ImJvZ25hIiwibGFzdE5hbWUiOiJib2duYSIsImF2YXRhciI6IiIsImlhdCI6MTcwNDc4NjM2MywiZXhwIjoxNzA0ODcyNzYzfQ.mPwH1vZVvHkVDg6adXuP83TWEmH3DZPHWPd7xEo8F60
Content-Type: application/json

{
  "oldPassword": "123",
  "newPassword": "123"
}

###

POST http://localhost:3000/api/auth/refresh HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1YWU4ODQ4NzBhNDYyYjc5MmRmMWU1NSIsImVtYWlsIjoiYWJ1c0BnbWFpbC5jb20iLCJmaXJzdE5hbWUiOiJib2duYSIsImxhc3ROYW1lIjoiYm9nbmEiLCJhdmF0YXIiOiIiLCJ0b2tlbklkIjoiNzQwNTljMjEtMzFjYy00YzgxLTgxM2UtNmNjODVmOTZjNThhIiwiaWF0IjoxNzA1OTM3NzMzLCJleHAiOjE3MDcyMzM3MzN9.Pwv2nW27N0jEmUMM9vgxBFnAYROXZve88HAHgw7KvK0
