POST http://localhost:3000/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "email": "bogda@gmail.com",
  "password": "123456fsdf",
  "firstName": "bogna",
  "lastName": "bogna"
}

###

POST http://localhost:3000/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "bogda@gmail.com",
  "password": "123456fsdf"
}

###

GET http://localhost:3000/api/auth/19234fcc-7907-483e-b1c5-f7bf58cf69a6 HTTP/1.1
