GET http://localhost:3003/api/file/65817544a79768499a03d801 HTTP/1.1

###

POST http://localhost:3003/api/file/upload HTTP/1.1
Content-Type: application/json

{
    "imageUri": "sssss.txt",
    "type": "avatar"
}
