GET http://localhost:3001/api/blog/?filter=like HTTP/1.1

###

POST http://localhost:3001/api/blog/video HTTP/1.1
Content-Type: application/json

{
    "name": "Video Title",
    "videoUrl": "https://www.youtube.com/watch?v=9bZkp7q19f0",
    "tags": ["tag1", "tag2"],
    "authorId": "5f0b5b9b9b9b9b9b9b9b9b9b"
}

###

POST http://localhost:3001/api/blog/text HTTP/1.1
Content-Type: application/json

{
    "name": "Text Title",
    "text": "Text content",
    "tags": ["tag1", "tag2"],
    "authorId": "5f0b5b9b9b9b9b9b9b9b9b9b",
    "anonsText": "Anons text"
}

###

POST http://localhost:3001/api/blog/quote HTTP/1.1
Content-Type: application/json

{
    "quote": "Quote content",
    "quoteAuthor": "Quote author",
    "tags": ["tag1", "tag2"],
    "authorId": "5f0b5b9b9b9b9b9b9b9b9b9b"
}

###

POST http://localhost:3001/api/blog/image HTTP/1.1
Content-Type: application/json

{
    "imageUrl": "https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png",
    "tags": ["tag1", "tag2"],
    "authorId": "5f0b5b9b9b9b9b9b9b9b9b9b"
}

###

POST http://localhost:3001/api/blog/link HTTP/1.1
Content-Type: application/json

{
    "description": "Link Description",
    "linkUrl": "https://www.google.com/",
    "tags": ["tag1", "tag2"],
    "authorId": "5f0b5b9b9b9b9b9b9b9b9b9b"
}

###

POST http://localhost:3001/api/blog/like/171e7bed-3df9-468f-831d-b13cf5cf1d71 HTTP/1.1

###

GET http://localhost:3001/api/blog/e82d4f63-3a8d-4d2f-ab96-5380cbae48a8 HTTP/1.1

###

DELETE http://localhost:3001/api/blog/e82d4f63-3a8d-4d2f-ab96-5380cbae48a8 HTTP/1.1

###

PATCH http://localhost:3001/api/blog/6b02f3b9-8765-4683-8964-27e61dcbc280 HTTP/1.1
Content-Type: application/json

{
    "linkUrl": "l"
}
