GET http://localhost:3001/api/blog HTTP/1.1

###

POST http://localhost:3001/api/blog/video HTTP/1.1
Content-Type: application/json

{
    "name": "Video Title",
    "videoUrl": "https://www.youtube.com/watch?v=9bZkp7q19f0",
    "tags": ["tag1", "tag2"],
    "authorId": "5f0b5b9b9b9b9b9b9b9b9b9b"
}

###

POST http://localhost:3001/api/blog/text HTTP/1.1
Content-Type: application/json

{
    "name": "Text Title",
    "text": "Text content",
    "tags": ["tag1", "tag2"],
    "authorId": "5f0b5b9b9b9b9b9b9b9b9b9b",
    "anonsText": "Anons text"
}

###

POST http://localhost:3001/api/blog/quote HTTP/1.1
Content-Type: application/json

{
    "quote": "Quote content",
    "quoteAuthor": "Quote author",
    "tags": ["tag1", "tag2"],
    "authorId": "5f0b5b9b9b9b9b9b9b9b9b9b"
}

###

POST http://localhost:3001/api/blog/image HTTP/1.1
Content-Type: application/json

{
    "imageUrl": "https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png",
    "tags": ["tag1", "tag2"],
    "authorId": "5f0b5b9b9b9b9b9b9b9b9b9b"
}

###

POST http://localhost:3001/api/blog/link HTTP/1.1
Content-Type: application/json

{
    "description": "Link Description",
    "linkUrl": "https://www.google.com/",
    "tags": ["tag1", "tag2"],
    "authorId": "5f0b5b9b9b9b9b9b9b9b9b9b"
}

###

POST http://localhost:3001/api/blog/like/c3de306b-1d61-47f7-8e04-a9656ba336b0 HTTP/1.1

###

GET http://localhost:3001/api/blog/c3de306b-1d61-47f7-8e04-a9656ba336b0 HTTP/1.1
